action: ['test']  # one of [train, train+valid, train+test, valid, test]
seed: 0
cuda: 0
data:
  type: EFO-1  # one of ['beta', 'EFO-1']
  data_folder: data/benchmark/FB15k-237
  cpu: 10
load:
  load_model: False
  checkpoint_path: null
  step: 0
output:
  output_path: null  # can be null, which means it will be auto_generated
  prefix: benchmark_log
train:
  negative_sample_size: 128  # for each positive sample
  batch_size: 512
  learning_rate: 0.0001
  steps: 450000
  log_every_steps: 100
  warm_up_steps: 225000
  evaluate_every_steps: 15000
  save_every_steps: 10000
  meta_queries:
  use_freeze: False
  freeze_formula_file: 'data/FB15k-237-betae/freeze_formulas_dumps.csv'
  use_distance: False   #  one of [False, root, leaf]
evaluate:  # only used when valid/test in action
  batch_size: 1000
  print: true
  meta_queries:
     - 0
     - 464
estimator:
  embedding: box # one of [Transe, box, beta, dm]
  beta:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    # evaluate_union: DM # one of [DM, DNF] after parsing it can be omitted
    gamma: 60
  box:
    entity_dim: 400
    relation_dim: 400
    offset_activation: none
    center_reg: 0.02
    gamma: 24
  dm:
    entity_dim: 2
    relation_dim: 2
    hidden_dim: 1600
    num_layers: 2
  logic:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    evaluate_union: DM
    gamma: 0.375
    t_norm: luk
    bounded: 1
    use_att: 1
    use_gtrans: 0
  cqd:
    entity_dim: 1000 # actually 2000
    relation_dim: 1000
    norm_type: product
  NewLook:
    entity_dim: 400
    relation_dim: 400
    center_reg: 0.2
    x_reg: 0.2 # \lambda in the paper

